name: ğŸš€ CI/CD Development

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: ğŸ“¦ Checkout Code
        uses: actions/checkout@v4

      - name: ğŸ§° Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¥ Install Dependencies
        run: npm install

      - name: ğŸ” Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: ğŸ› ï¸ Build Docker Image
        run: docker build --no-cache -t kanzen523/gajadicair-api:latest .

      - name: ğŸ“¤ Push Docker Image
        run: docker push kanzen523/gajadicair-api:latest

      - name: ğŸš¢ Deploy to VPS Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "ğŸ” Pulling latest Docker image..."
            docker pull kanzen523/gajadicair-api:latest

            echo "ğŸ›‘ Stopping and removing old container (if exists)..."
            docker stop gajadicair-api || true
            docker rm gajadicair-api || true

            echo "ğŸš€ Running new container..."
            docker run -d \
              --name gajadicair-api \
              --network postgis-setup_postgis-network \
              --restart unless-stopped \
              -e NODE_ENV="development" \
              -e APP_NAME="${{ vars.APP_NAME }}" \
              -e JWT_SECRET="${{ vars.JWT_SECRET }}" \
              -e JWT_EXPIRES_IN="${{ vars.JWT_EXPIRES_IN }}" \
              -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
              -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
              -e GOOGLE_REDIRECT_URI="${{ secrets.GOOGLE_REDIRECT_URI }}" \
              -e S3_END_POINT="${{ vars.S3_END_POINT }}" \
              -e S3_ACCESS_KEY_ID="${{ secrets.S3_ACCESS_KEY_ID }}" \
              -e S3_SECRET_ACCESS_KEY_ID="${{ secrets.S3_SECRET_ACCESS_KEY_ID }}" \
              -e S3_BUCKET_NAME="${{ vars.S3_BUCKET_NAME }}" \
              -p ${{ vars.PORT }}:3000 \
              kanzen523/gajadicair-api:latest

            echo "ğŸ§¹ Cleaning up unused Docker resources..."
            docker system prune -f

            echo "ğŸ”„ Running Prisma migrations..."
            docker exec gajadicair-api npx prisma migrate deploy

            echo "âœ… Deployment to Development environment completed successfully!"