name: üöÄ CI/CD Development

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: üì¶ Checkout Code
        uses: actions/checkout@v4

      - name: üß∞ Setup Bun v2
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: üì• Install Dependencies
        run: bun install

      - name: üîê Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: üõ†Ô∏è Build Docker Image
        run: docker build --no-cache -t kanzen523/gajadicair-api:latest .

      - name: üì§ Push Docker Image
        run: docker push kanzen523/gajadicair-api:latest

      - name: üö¢ Deploy to VPS Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "üîÅ Pulling latest Docker image..."
            docker pull kanzen523/gajadicair-api:latest

            echo "üõë Stopping and removing old container (if exists)..."
            docker stop gajadicair-api || true
            docker rm gajadicair-api || true

            echo "üöÄ Running new container..."
            docker run -d \
              --name gajadicair-api \
              --network postgis-setup_postgis-network \
              --restart unless-stopped \
              -e NODE_ENV="development" \
              -e APP_NAME="${{ vars.APP_NAME }}" \
              -e JWT_SECRET="${{ vars.JWT_SECRET }}" \
              -e JWT_EXPIRES_IN="${{ vars.JWT_EXPIRES_IN }}" \
              -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
              -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
              -e GOOGLE_REDIRECT_URI="${{ secrets.GOOGLE_REDIRECT_URI }}" \
              -e S3_END_POINT="${{ vars.S3_END_POINT }}" \
              -e S3_ACCESS_KEY_ID="${{ secrets.S3_ACCESS_KEY_ID }}" \
              -e S3_SECRET_ACCESS_KEY_ID="${{ secrets.S3_SECRET_ACCESS_KEY_ID }}" \
              -e S3_BUCKET_NAME="${{ vars.S3_BUCKET_NAME }}" \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e MAILER_HOST="${{ vars.MAILER_HOST }}" \
              -e MAILER_PORT="${{ vars.MAILER_PORT }}" \
              -e MAILER_USER="${{ secrets.MAILER_USER }}" \
              -e MAILER_PASSWORD="${{ secrets.MAILER_PASSWORD }}" \
              -e MAILER_TLS_REJECT_UNAUTHORIZED="${{ vars.MAILER_TLS_REJECT_UNAUTHORIZED }}" \
              -p ${{ vars.PORT }}:3000 \
              kanzen523/gajadicair-api:latest

            echo "üßπ Cleaning up unused Docker resources..."
            docker system prune -f

            echo "üîÑ Running Prisma migrations..."
            docker exec gajadicair-api bun prisma migrate deploy

            echo "‚úÖ Deployment to Development environment completed successfully!"
